from mlgames.config.initial_connect4_config import InitialConnect4Config
from mlgames.config.initial_tictactoe_config import InitialTicTacToeConfig
from mlgames.config.tictactoe_learnanynonlosing_config import TicTacToeLearnAnyNonLosingConfig

CURRENT_CONFIG = TicTacToeLearnAnyNonLosingConfig()
